### PR TITLE
Work on #50

### PR DESCRIPTION
**Pull request by dwinter**
Taking on the low-hanging fruit:

* New function strip_ott_ids
* docs and tests for the function
* note in the NEWS file about it's use

Only question is whether the `tol` R files/tests is the best place for this to live?

### CODE REVIEW

**Comment by dwinter** [comment]
oh, and after the move to ropensci I can't push directly to the main repo.

Not a huge problem, as now `rotl` is a bit more mature it's probably good to have someone overseeing the 'big picutre' of its development.

**Comment by fmichonneau** [comment]
Thanks @dwinter!

It looks like the Rd file didn't make it to the PR. Could you please add it?

The location of the test is fine for now.

I'll ping Scott to ask him to add you to the repo.

**Comment by dwinter** [comment]
Added and pushed -- I make that mistake so often, `devtools::document()` should come with a "did you remember to git add the new .Rd files" warning :smile:

**Comment by fmichonneau** [comment]
Perfect, thanks! You can now push directly to the repo.

**Pull request merged**
